spring.application.name=core-financier
spring.profiles.active=dev

# Mindee API Key loading
mindee.api.key=${MINDEE_API_KEY:test}

# JWT Configurations
jwt.secret=${JWT_SECRET:TEST_SECRET_KEY_CHANGE_IN_PROD_VERY_LONG_STRING_REQUIRED}
jwt.expiration=${JWT_EXPIRATION:3600000}
