spring.application.name=core-financier
spring.profiles.active=dev

# Mindee API Key loading
mindee.api.key=${MINDEE_API_KEY}

# JWT Configurations
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
